### ISSUE TITLE
broken the scenario for Spoke to Spoke connectivity using a VPN Gateway :

### ISSUE THREAD

**Issue by nicolgit** [nicolgit/hub-and-spoke-playground#21]
This commit seems to have broken the scenario for Spoke to Spoke connectivity using a VPN Gateway :
https://github.com/nicolgit/hub-and-spoke-playground/blob/main/scenarios/ping-any-to-any-gateway.md

After reverting to the VpnGw1 SKU the Spoke to Spoke connectivity using a VPN Gateway works.

Note: I reverted to the **VpnGw1** SKU by creating a non-zonal IP address using the **2020-08-01** api version : 
`vnetGatewayIP 'Microsoft.Network/publicIPAddresses@2020-08-01' `

_Originally posted by @joblini in https://github.com/nicolgit/hub-and-spoke-playground/issues/20#issuecomment-2308945865_

**Comment by joblini** [comment]
It is not necessary to change the SKU of the VPN Gateway to VpnGw1Az.   The existing SKU VpnGw1 will continue to work if the SKU of the public IP is updated as follows :
![image](https://github.com/user-attachments/assets/461ac604-3bef-4cd8-b595-966f830881d1)

**Comment by joblini** [comment]
More information here :  https://azure.microsoft.com/en-us/updates/zone-behavior-change

**Comment by nicolgit** [comment]
fixed in 262afe56ca9fc3371bd876af255a45dfdc772a54
